# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    error_controller: 'App\Controller\ErrorController::accesoDenegado'  # Solo para el error 403

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

