security:
    # Registrar los hashers de contraseña
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuración de los proveedores de usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email # Campo único para identificar al usuario
        users_in_memory: { memory: null }

    # Configuración de los firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider # Se cambió para usar el proveedor correcto
            custom_authenticator: App\Security\UsuarioAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    # Control de acceso
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
